### ISSUE TITLE
S-10: Initial README Documentation

### ISSUE THREAD

**Issue by desslinga** [wafffly/closetr#23]
**Description**: Documentation should be provided in the README. The audience of this document would be be both developers (potential contributers) as well as users of the project.

**Required**
- High level introduction and description of the project.
- Description of users of the project.
- Technology stack used, and justification.
- Future plans for project.

**Development Estimates**
- Development: 12 hours.

**Comment by JoshuaConcon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [README](https://trello.com/c/92q0dkTV/2-readme)
