### ISSUE TITLE
S-35: Setup Angular Tests

### ISSUE THREAD

**Issue by JoshuaConcon** [wafffly/closetr#70]
**Description**
Add test suite for Angular portion. 
[Reference](https://medium.com/@dhormale/automate-end-to-end-e2e-testing-for-angular-7-using-protractor-jasmine-4ce171aaeedc)

**Required**
- Cleanup so that running `ng test` don't result in any failures.

**Development Estimates**
- 8 hours.

**Comment by desslinga** [comment]
Story needs to be broken up to separate stories for each test suite.
