### ISSUE TITLE
S-43: Create API for Log Outfit Functionality

### ISSUE THREAD

**Issue by desslinga** [wafffly/closetr#83]
**Description**: There is currently no backend API to support the Log Outfit function. A new API should be created which takes an array of clothing as input, the date (possibly), and the username (ID), and stores that entry in the database.

**Required**
Backend: 
- [x] Create model for outfit entry, which includes `clothingID`, `userID`, and `date`.
- [x] Create API for logging an outfit, which uses POST to receive `clothingID`, `userID`, `token`, and `date`. The user must be authenticated using their token, then the entry is added to the database.
- [x] Create API for getting all clothes that are logged for today's date (or a specific date). Takes `date` and `userID` as input and returns logged clothes for that date.
- [x] Connect the API to the Log Outfit Service. 

**Development Estimates**
- Development: 24 hours.

**Comment by JoshuaConcon** [comment]
Created `oufit_entry` route in API portion, it's ready to be tested on the Angular side.

**Comment by desslinga** [comment]
Added new requirement for API.
